# This is a basic workflow to help you get started with Actions

name: Codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test package with coverage
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    - name: update pip
      run: 
        python -m pip install --upgrade pip
    - name: Install tox
      run: 
        pip install tox tox-gh-actions
    - name: Install package
      run: 
        pip install -e . 
    - name: Install dev requirements
      run: 
        pip install -e ".[dev]"
        
    - name: Run tests and collect coverage
      run: pytest --cov=cga_py --cov-report=xml tests/
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
